### ISSUE TITLE
cdk-scaffold not on Maven Central

### ISSUE THREAD

**Issue by JonasSchaub** [cdk/cdk-scaffold#16] opened 2023-09-12 08:21 UTC
Good morning,
thanks for doing the release @egonw . 
Apparently, the artifact did not get pushed to Maven Central. What do we need to do there?

**Comment by johnmay** [comment] 2023-09-12 09:02
Did you push it?

**Comment by JonasSchaub** [comment] 2023-09-12 09:08
I didn't do anything there, I don't know the necessary course of action regarding this, sorry.

**Comment by johnmay** [comment] 2023-09-12 14:01
If the POM is set up correctly I think Egon just needs to do `mvn deploy -Possrh`

**Comment by egonw** [comment] 2023-09-12 19:10
Weird... did you try it, or just use the search engine? That index needs catching up, but normally happens within 24 

Okay, I scrolled back in my console history... my bad. I pushed the 2.9-SNAPSHOT and the last 2.8-SNAPSHOT, but seem to have forgotten to push the 2.8 itself :/

I'll fix that when back home (and on stable network).

Sorry!

**Comment by johnmay** [comment] 2023-09-12 19:32
https://s01.oss.sonatype.org/#nexus-search;quick~cdk-scaffold

**Comment by egonw** [comment] 2023-09-12 19:44
I managed to push it from the train:

```
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ cdk-scaffold ---
Uploading to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/2.8/cdk-scaffold-2.8.jar
Uploaded to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/2.8/cdk-scaffold-2.8.jar (41 kB at 6.0 kB/s)
Uploading to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/2.8/cdk-scaffold-2.8.pom
Uploaded to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/2.8/cdk-scaffold-2.8.pom (22 kB at 20 kB/s)
Downloading from ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/maven-metadata.xml
Uploading to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/maven-metadata.xml
Uploaded to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/org/openscience/cdk/cdk-scaffold/maven-metadata.xml (307 B at 322 B/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.699 s
[INFO] Finished at: 2023-09-12T21:14:15+02:00
[INFO] ------------------------------------------------------------------------
```

It says `staging`. I guess since this is the first formal release, it needs some manual intervention. I will keep you posted.

**Comment by JonasSchaub** [comment] 2023-09-13 09:09
Thanks @egonw !

>It says staging. I guess since this is the first formal release, it needs some manual intervention. I will keep you posted.

You probably have to log into the sonatype repository manager https://s01.oss.sonatype.org/#welcome (via the account that the artifact got staged through) and manually trigger the final release. I had this "issue" before with my own projects.

**Comment by egonw** [comment] 2023-09-13 14:45
I'll check tonight at home

**Comment by egonw** [comment] 2023-09-14 12:46
It was deployed, and I actually had deployed originally too, tho I seemed to have overlooked that when scrolling back. But in both cases, before your message and just now, staging works, but stops on the Sonatype with a "No IQ Server data recorded" error message. The "Release" button is disabled. I'm trying to resolve this.

**Comment by JonasSchaub** [comment] 2023-09-14 12:52
Ok, thank you!

**Comment by egonw** [comment] 2023-09-14 12:59
I filed a support request. I hope to solve this soon.

**Comment by egonw** [comment] 2023-09-19 06:23
Okay, the manual trigger is "closing the staged release". It ran into a few problems. These did not show up during the SNAPSHOT phase, so I will have to make a 2.8.1 release. Will work on this asap.

**Comment by egonw** [comment] 2023-09-22 21:23
Okay, it seems it worked now: https://s01.oss.sonatype.org/content/repositories/releases/org/openscience/cdk/cdk-scaffold/2.8/cdk-scaffold-2.8.pom

I kept it 2.8, since there was no release yet and nothing in the code changed.

**Comment by egonw** [comment] 2023-09-23 09:11
Confirmed: https://search.maven.org/artifact/org.openscience.cdk/cdk-scaffold/2.8/jar

**Closed as completed by egonw** 2023-09-23 09:11 UTC
